spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/tweetapp
      
  application:
    name: tweetservice
    
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: tweetkafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    
    producer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
server:
  port: 8081
logging:
  file:
    name: C:/Tweet-App-2/MidTier/tweetLog.log